//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaITM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id { get; set; }
        public int idAgencia { get; set; }
        public int idCliente { get; set; }
        public int idVehiculo { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public decimal total { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
